services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8000:80"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    user: wwwuser
    volumes:
      - .:/var/www/html:rw
    networks:
      - laravel
    # make startup-laravel.sh executable & run it
    command: >
      sh -c "chmod +x /var/www/html/startup_laravel.sh;
             /var/www/html/startup_laravel.sh;"

  mariadb:
    image: mariadb
    restart: unless-stopped
    user: root
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dockertestrootpassword
      - MYSQL_DATABASE=fitnesstracker-db
      - MYSQL_USER=fitnesstracker
      - MYSQL_PASSWORD=fitnesstrackerpwd
    ports:
      - "9002:3306"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
        - laravel

  node:
    build:
      context: .
      target: node-dev
    user: node
    volumes:
      - .:/var/www/html:rw
    networks:
        - laravel
    ports:
        - "5173:5173"
    # make startup-node.sh executable & run it
    command: >
      sh -c "chmod +x /var/www/html/startup_node.sh;
             /var/www/html/startup_node.sh;"

networks:
  laravel:
    driver: bridge

volumes:
  db-data:
